const express=require('express')
const { createProductController, getAllProductConroller, getProductByIdController, updateProductController, deleteProductController } = require('./productControllers')
const authMiddleware = require('../../middleware/authMiddleware')
const roleMiddleware = require('../../middleware/roleMiddleware')
const router=express.Router()
router.post('/create/:id',authMiddleware,roleMiddleware(['admin']),createProductController)
router.get('/',getAllProductConroller)
router.get('/getProduct/:id',authMiddleware,getProductByIdController)
router.put('/updateProduct/:id',authMiddleware,roleMiddleware(['admin']),updateProductController)
router.delete('/deleteProduct/:id',authMiddleware,roleMiddleware(['admin']),deleteProductController)
module.exports=router